// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A request message to initiate patching across Compute Engine
/// instances.
public struct ExecutePatchJobRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The project in which to run this patch in the form `projects/*`
  public var parent: Swift.String = Swift.String()

  /// Description of the patch job. Length of the description is limited
  /// to 1024 characters.
  public var description: Swift.String = Swift.String()

  /// Required. Instances to patch, either explicitly or filtered by some
  /// criteria such as zone or labels.
  public var instanceFilter: PatchInstanceFilter? = nil

  /// Patch configuration being applied. If omitted, instances are
  /// patched using the default configurations.
  public var patchConfig: PatchConfig? = nil

  /// Duration of the patch job. After the duration ends, the patch job
  /// times out.
  public var duration: GoogleWKT.Duration? = nil

  /// If this patch is a dry-run only, instances are contacted but
  /// will do nothing.
  public var dryRun: Swift.Bool = Swift.Bool()

  /// Display name for this patch job. This does not have to be unique.
  public var displayName: Swift.String = Swift.String()

  /// Rollout strategy of the patch job.
  public var rollout: PatchRollout? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExecutePatchJobRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExecutePatchJobRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let description = CodingKeys(stringValue: "description")
    static let instanceFilter = CodingKeys(stringValue: "instanceFilter")
    static let patchConfig = CodingKeys(stringValue: "patchConfig")
    static let duration = CodingKeys(stringValue: "duration")
    static let dryRun = CodingKeys(stringValue: "dryRun")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let rollout = CodingKeys(stringValue: "rollout")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "description",
      "instanceFilter",
      "patchConfig",
      "duration",
      "dryRun",
      "displayName",
      "rollout",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.instanceFilter = try container.decodeIfPresent(
      PatchInstanceFilter.self, forKey: .instanceFilter)
    self.patchConfig = try container.decodeIfPresent(PatchConfig.self, forKey: .patchConfig)
    self.duration = try container.decodeIfPresent(GoogleWKT.Duration.self, forKey: .duration)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .dryRun) {
      self.dryRun = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    self.rollout = try container.decodeIfPresent(PatchRollout.self, forKey: .rollout)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.instanceFilter, forKey: .instanceFilter)
    try container.encodeIfPresent(self.patchConfig, forKey: .patchConfig)
    try container.encodeIfPresent(self.duration, forKey: .duration)
    try container.encode(self.dryRun, forKey: .dryRun)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encodeIfPresent(self.rollout, forKey: .rollout)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.osconfig.v1.ExecutePatchJobRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
