// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message encapsulating a value that can be either absolute ("fixed") or
/// relative ("percent") to a value.
public struct FixedOrPercent: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Type of the value.
  public var mode: OneOf_Mode? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FixedOrPercent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FixedOrPercent().with { $0.fixed = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let fixed = CodingKeys(stringValue: "fixed")
    static let percent = CodingKeys(stringValue: "percent")

    static let _knownKeys: Set<Swift.String> = [
      "fixed",
      "percent",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var mode: OneOf_Mode? = nil
    let modeCheckAndSet = {
      if mode != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'mode'"
          ))
      }
      mode = $0
    }
    if let fixed = try container.decodeIfPresent(Swift.Int32.self, forKey: .fixed) {
      try modeCheckAndSet(.fixed(fixed))
    }
    if let percent = try container.decodeIfPresent(Swift.Int32.self, forKey: .percent) {
      try modeCheckAndSet(.percent(percent))
    }
    self.mode = mode
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.mode {
      switch choice {
      case .fixed(let value):
        try container.encode(value, forKey: .fixed)
      case .percent(let value):
        try container.encode(value, forKey: .percent)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Type of the value.
  public enum OneOf_Mode: Codable, Equatable, Sendable {
    /// Specifies a fixed value.
    case fixed(Swift.Int32)
    /// Specifies the relative value defined as a percentage, which will be
    /// multiplied by a reference value.
    case percent(Swift.Int32)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.osconfig.v1.FixedOrPercent"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
