// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleType
@_spi(GoogleCloudInternal) import GoogleWKT

/// This API resource represents the available inventory data for a
/// Compute Engine virtual machine (VM) instance at a given point in time.
///
/// You can use this API resource to determine the inventory data of your VM.
///
/// For more information, see [Information provided by OS inventory
/// management](https://cloud.google.com/compute/docs/instances/os-inventory-management#data-collected).
public struct Inventory: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The `Inventory` API resource name.
  ///
  /// Format:
  /// `projects/{project_number}/locations/{location}/instances/{instance_id}/inventory`
  public var name: Swift.String = Swift.String()

  /// Base level operating system information for the VM.
  public var osInfo: Inventory.OsInfo? = nil

  /// Inventory items related to the VM keyed by an opaque unique identifier for
  /// each inventory item.  The identifier is unique to each distinct and
  /// addressable inventory item and will change, when there is a new package
  /// version.
  public var items: [Swift.String: Inventory.Item] = [:]

  /// Output only. Timestamp of the last reported inventory for the VM.
  public var updateTime: GoogleWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Inventory`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Inventory().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let osInfo = CodingKeys(stringValue: "osInfo")
    static let items = CodingKeys(stringValue: "items")
    static let updateTime = CodingKeys(stringValue: "updateTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "osInfo",
      "items",
      "updateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.osInfo = try container.decodeIfPresent(Inventory.OsInfo.self, forKey: .osInfo)
    if let value = try container.decodeIfPresent(
      [Swift.String: Inventory.Item].self, forKey: .items)
    {
      self.items = value
    }
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.osInfo, forKey: .osInfo)
    try container.encode(self.items, forKey: .items)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Operating system information for the VM.
  public struct OsInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The VM hostname.
    public var hostname: Swift.String = Swift.String()

    /// The operating system long name.
    /// For example 'Debian GNU/Linux 9' or 'Microsoft Window Server 2019
    /// Datacenter'.
    public var longName: Swift.String = Swift.String()

    /// The operating system short name.
    /// For example, 'windows' or 'debian'.
    public var shortName: Swift.String = Swift.String()

    /// The version of the operating system.
    public var version: Swift.String = Swift.String()

    /// The system architecture of the operating system.
    public var architecture: Swift.String = Swift.String()

    /// The kernel version of the operating system.
    public var kernelVersion: Swift.String = Swift.String()

    /// The kernel release of the operating system.
    public var kernelRelease: Swift.String = Swift.String()

    /// The current version of the OS Config agent running on the VM.
    public var osconfigAgentVersion: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `OsInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OsInfo().with { $0.hostname = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let hostname = CodingKeys(stringValue: "hostname")
      static let longName = CodingKeys(stringValue: "longName")
      static let shortName = CodingKeys(stringValue: "shortName")
      static let version = CodingKeys(stringValue: "version")
      static let architecture = CodingKeys(stringValue: "architecture")
      static let kernelVersion = CodingKeys(stringValue: "kernelVersion")
      static let kernelRelease = CodingKeys(stringValue: "kernelRelease")
      static let osconfigAgentVersion = CodingKeys(stringValue: "osconfigAgentVersion")

      static let _knownKeys: Set<Swift.String> = [
        "hostname",
        "longName",
        "shortName",
        "version",
        "architecture",
        "kernelVersion",
        "kernelRelease",
        "osconfigAgentVersion",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostname) {
        self.hostname = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .longName) {
        self.longName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .shortName) {
        self.shortName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
        self.version = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .architecture) {
        self.architecture = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kernelVersion) {
        self.kernelVersion = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kernelRelease) {
        self.kernelRelease = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .osconfigAgentVersion)
      {
        self.osconfigAgentVersion = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.hostname, forKey: .hostname)
      try container.encode(self.longName, forKey: .longName)
      try container.encode(self.shortName, forKey: .shortName)
      try container.encode(self.version, forKey: .version)
      try container.encode(self.architecture, forKey: .architecture)
      try container.encode(self.kernelVersion, forKey: .kernelVersion)
      try container.encode(self.kernelRelease, forKey: .kernelRelease)
      try container.encode(self.osconfigAgentVersion, forKey: .osconfigAgentVersion)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.osconfig.v1.Inventory.OsInfo"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A single piece of inventory on a VM.
  public struct Item: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Identifier for this item, unique across items for this VM.
    public var id: Swift.String = Swift.String()

    /// The origin of this inventory item.
    public var originType: Inventory.Item.OriginType = Inventory.Item.OriginType()

    /// When this inventory item was first detected.
    public var createTime: GoogleWKT.Timestamp? = nil

    /// When this inventory item was last modified.
    public var updateTime: GoogleWKT.Timestamp? = nil

    /// The specific type of inventory, correlating to its specific details.
    public var type: Inventory.Item.Type_ = Inventory.Item.Type_()

    /// Specific details of this inventory item based on its type.
    public var details: OneOf_Details? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Item`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Item().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let id = CodingKeys(stringValue: "id")
      static let originType = CodingKeys(stringValue: "originType")
      static let createTime = CodingKeys(stringValue: "createTime")
      static let updateTime = CodingKeys(stringValue: "updateTime")
      static let type = CodingKeys(stringValue: "type")
      static let installedPackage = CodingKeys(stringValue: "installedPackage")
      static let availablePackage = CodingKeys(stringValue: "availablePackage")

      static let _knownKeys: Set<Swift.String> = [
        "id",
        "originType",
        "createTime",
        "updateTime",
        "type",
        "installedPackage",
        "availablePackage",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
        self.id = value
      }
      if let value = try container.decodeIfPresent(
        Inventory.Item.OriginType.self, forKey: .originType)
      {
        self.originType = value
      }
      self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
      self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
      if let value = try container.decodeIfPresent(Inventory.Item.Type_.self, forKey: .type) {
        self.type = value
      }

      var details: OneOf_Details? = nil
      let detailsCheckAndSet = {
        if details != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'details'"))
        }
        details = $0
      }
      if let installedPackage = try container.decodeIfPresent(
        Inventory.SoftwarePackage?.self, forKey: .installedPackage)
      {
        try detailsCheckAndSet(.installedPackage(installedPackage))
      }
      if let availablePackage = try container.decodeIfPresent(
        Inventory.SoftwarePackage?.self, forKey: .availablePackage)
      {
        try detailsCheckAndSet(.availablePackage(availablePackage))
      }
      self.details = details
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.id, forKey: .id)
      try container.encode(self.originType, forKey: .originType)
      try container.encodeIfPresent(self.createTime, forKey: .createTime)
      try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
      try container.encode(self.type, forKey: .type)

      if let choice = self.details {
        switch choice {
        case .installedPackage(let value):
          try container.encode(value, forKey: .installedPackage)
        case .availablePackage(let value):
          try container.encode(value, forKey: .availablePackage)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The origin of a specific inventory item.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum OriginType: Codable, Equatable, Sendable {
      /// Invalid. An origin type must be specified.
      case unspecified
      /// This inventory item was discovered as the result of the agent
      /// reporting inventory via the reporting API.
      case inventoryReport
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .inventoryReport: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "ORIGIN_TYPE_UNSPECIFIED"
        case .inventoryReport: return "INVENTORY_REPORT"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OriginType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "ORIGIN_TYPE_UNSPECIFIED": self = .unspecified
        case "INVENTORY_REPORT": self = .inventoryReport
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OriginType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .inventoryReport
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("ORIGIN_TYPE_UNSPECIFIED")
        case .inventoryReport: return try container.encode("INVENTORY_REPORT")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The different types of inventory that are tracked on a VM.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum Type_: Codable, Equatable, Sendable {
      /// Invalid. An type must be specified.
      case unspecified
      /// This represents a package that is installed on the VM.
      case installedPackage
      /// This represents an update that is available for a package.
      case availablePackage
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .installedPackage: return 1
        case .availablePackage: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "TYPE_UNSPECIFIED"
        case .installedPackage: return "INSTALLED_PACKAGE"
        case .availablePackage: return "AVAILABLE_PACKAGE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TYPE_UNSPECIFIED": self = .unspecified
        case "INSTALLED_PACKAGE": self = .installedPackage
        case "AVAILABLE_PACKAGE": self = .availablePackage
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .installedPackage
        case 2: self = .availablePackage
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
        case .installedPackage: return try container.encode("INSTALLED_PACKAGE")
        case .availablePackage: return try container.encode("AVAILABLE_PACKAGE")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Specific details of this inventory item based on its type.
    public enum OneOf_Details: Codable, Equatable, Sendable {
      /// Software package present on the VM instance.
      indirect case installedPackage(Inventory.SoftwarePackage?)
      /// Software package available to be installed on the VM instance.
      indirect case availablePackage(Inventory.SoftwarePackage?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.osconfig.v1.Inventory.Item"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Software package information of the operating system.
  public struct SoftwarePackage: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Information about the different types of software packages.
    public var details: OneOf_Details? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SoftwarePackage`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SoftwarePackage().with { $0.yumPackage = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let yumPackage = CodingKeys(stringValue: "yumPackage")
      static let aptPackage = CodingKeys(stringValue: "aptPackage")
      static let zypperPackage = CodingKeys(stringValue: "zypperPackage")
      static let googetPackage = CodingKeys(stringValue: "googetPackage")
      static let zypperPatch = CodingKeys(stringValue: "zypperPatch")
      static let wuaPackage = CodingKeys(stringValue: "wuaPackage")
      static let qfePackage = CodingKeys(stringValue: "qfePackage")
      static let cosPackage = CodingKeys(stringValue: "cosPackage")
      static let windowsApplication = CodingKeys(stringValue: "windowsApplication")

      static let _knownKeys: Set<Swift.String> = [
        "yumPackage",
        "aptPackage",
        "zypperPackage",
        "googetPackage",
        "zypperPatch",
        "wuaPackage",
        "qfePackage",
        "cosPackage",
        "windowsApplication",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var details: OneOf_Details? = nil
      let detailsCheckAndSet = {
        if details != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'details'"))
        }
        details = $0
      }
      if let yumPackage = try container.decodeIfPresent(
        Inventory.VersionedPackage?.self, forKey: .yumPackage)
      {
        try detailsCheckAndSet(.yumPackage(yumPackage))
      }
      if let aptPackage = try container.decodeIfPresent(
        Inventory.VersionedPackage?.self, forKey: .aptPackage)
      {
        try detailsCheckAndSet(.aptPackage(aptPackage))
      }
      if let zypperPackage = try container.decodeIfPresent(
        Inventory.VersionedPackage?.self, forKey: .zypperPackage)
      {
        try detailsCheckAndSet(.zypperPackage(zypperPackage))
      }
      if let googetPackage = try container.decodeIfPresent(
        Inventory.VersionedPackage?.self, forKey: .googetPackage)
      {
        try detailsCheckAndSet(.googetPackage(googetPackage))
      }
      if let zypperPatch = try container.decodeIfPresent(
        Inventory.ZypperPatch?.self, forKey: .zypperPatch)
      {
        try detailsCheckAndSet(.zypperPatch(zypperPatch))
      }
      if let wuaPackage = try container.decodeIfPresent(
        Inventory.WindowsUpdatePackage?.self, forKey: .wuaPackage)
      {
        try detailsCheckAndSet(.wuaPackage(wuaPackage))
      }
      if let qfePackage = try container.decodeIfPresent(
        Inventory.WindowsQuickFixEngineeringPackage?.self, forKey: .qfePackage)
      {
        try detailsCheckAndSet(.qfePackage(qfePackage))
      }
      if let cosPackage = try container.decodeIfPresent(
        Inventory.VersionedPackage?.self, forKey: .cosPackage)
      {
        try detailsCheckAndSet(.cosPackage(cosPackage))
      }
      if let windowsApplication = try container.decodeIfPresent(
        Inventory.WindowsApplication?.self, forKey: .windowsApplication)
      {
        try detailsCheckAndSet(.windowsApplication(windowsApplication))
      }
      self.details = details
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.details {
        switch choice {
        case .yumPackage(let value):
          try container.encode(value, forKey: .yumPackage)
        case .aptPackage(let value):
          try container.encode(value, forKey: .aptPackage)
        case .zypperPackage(let value):
          try container.encode(value, forKey: .zypperPackage)
        case .googetPackage(let value):
          try container.encode(value, forKey: .googetPackage)
        case .zypperPatch(let value):
          try container.encode(value, forKey: .zypperPatch)
        case .wuaPackage(let value):
          try container.encode(value, forKey: .wuaPackage)
        case .qfePackage(let value):
          try container.encode(value, forKey: .qfePackage)
        case .cosPackage(let value):
          try container.encode(value, forKey: .cosPackage)
        case .windowsApplication(let value):
          try container.encode(value, forKey: .windowsApplication)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Information about the different types of software packages.
    public enum OneOf_Details: Codable, Equatable, Sendable {
      /// Yum package info.
      /// For details about the yum package manager, see
      /// https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/ch-yum.
      indirect case yumPackage(Inventory.VersionedPackage?)
      /// Details of an APT package.
      /// For details about the apt package manager, see
      /// https://wiki.debian.org/Apt.
      indirect case aptPackage(Inventory.VersionedPackage?)
      /// Details of a Zypper package.
      /// For details about the Zypper package manager, see
      /// https://en.opensuse.org/SDB:Zypper_manual.
      indirect case zypperPackage(Inventory.VersionedPackage?)
      /// Details of a Googet package.
      ///  For details about the googet package manager, see
      ///  https://github.com/google/googet.
      indirect case googetPackage(Inventory.VersionedPackage?)
      /// Details of a Zypper patch.
      /// For details about the Zypper package manager, see
      /// https://en.opensuse.org/SDB:Zypper_manual.
      indirect case zypperPatch(Inventory.ZypperPatch?)
      /// Details of a Windows Update package.
      /// See https://docs.microsoft.com/en-us/windows/win32/api/_wua/ for
      /// information about Windows Update.
      indirect case wuaPackage(Inventory.WindowsUpdatePackage?)
      /// Details of a Windows Quick Fix engineering package.
      /// See
      /// https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-quickfixengineering
      /// for info in Windows Quick Fix Engineering.
      indirect case qfePackage(Inventory.WindowsQuickFixEngineeringPackage?)
      /// Details of a COS package.
      indirect case cosPackage(Inventory.VersionedPackage?)
      /// Details of Windows Application.
      indirect case windowsApplication(Inventory.WindowsApplication?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.osconfig.v1.Inventory.SoftwarePackage"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information related to the a standard versioned package.  This includes
  /// package info for APT, Yum, Zypper, and Googet package managers.
  public struct VersionedPackage: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The name of the package.
    public var packageName: Swift.String = Swift.String()

    /// The system architecture this package is intended for.
    public var architecture: Swift.String = Swift.String()

    /// The version of the package.
    public var version: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `VersionedPackage`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VersionedPackage().with { $0.packageName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let packageName = CodingKeys(stringValue: "packageName")
      static let architecture = CodingKeys(stringValue: "architecture")
      static let version = CodingKeys(stringValue: "version")

      static let _knownKeys: Set<Swift.String> = [
        "packageName",
        "architecture",
        "version",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .packageName) {
        self.packageName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .architecture) {
        self.architecture = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
        self.version = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.packageName, forKey: .packageName)
      try container.encode(self.architecture, forKey: .architecture)
      try container.encode(self.version, forKey: .version)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.osconfig.v1.Inventory.VersionedPackage"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Details related to a Zypper Patch.
  public struct ZypperPatch: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The name of the patch.
    public var patchName: Swift.String = Swift.String()

    /// The category of the patch.
    public var category: Swift.String = Swift.String()

    /// The severity specified for this patch
    public var severity: Swift.String = Swift.String()

    /// Any summary information provided about this patch.
    public var summary: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ZypperPatch`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ZypperPatch().with { $0.patchName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let patchName = CodingKeys(stringValue: "patchName")
      static let category = CodingKeys(stringValue: "category")
      static let severity = CodingKeys(stringValue: "severity")
      static let summary = CodingKeys(stringValue: "summary")

      static let _knownKeys: Set<Swift.String> = [
        "patchName",
        "category",
        "severity",
        "summary",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .patchName) {
        self.patchName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .category) {
        self.category = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .severity) {
        self.severity = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .summary) {
        self.summary = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.patchName, forKey: .patchName)
      try container.encode(self.category, forKey: .category)
      try container.encode(self.severity, forKey: .severity)
      try container.encode(self.summary, forKey: .summary)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.osconfig.v1.Inventory.ZypperPatch"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Details related to a Windows Update package.
  /// Field data and names are taken from Windows Update API IUpdate Interface:
  /// https://docs.microsoft.com/en-us/windows/win32/api/_wua/
  /// Descriptive fields like title, and description are localized based on
  /// the locale of the VM being updated.
  public struct WindowsUpdatePackage: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The localized title of the update package.
    public var title: Swift.String = Swift.String()

    /// The localized description of the update package.
    public var description: Swift.String = Swift.String()

    /// The categories that are associated with this update package.
    public var categories: [Inventory.WindowsUpdatePackage.WindowsUpdateCategory] = []

    /// A collection of Microsoft Knowledge Base article IDs that are associated
    /// with the update package.
    public var kbArticleIds: [Swift.String] = []

    /// A hyperlink to the language-specific support information for the update.
    public var supportUrl: Swift.String = Swift.String()

    /// A collection of URLs that provide more information about the update
    /// package.
    public var moreInfoUrls: [Swift.String] = []

    /// Gets the identifier of an update package.  Stays the same across
    /// revisions.
    public var updateId: Swift.String = Swift.String()

    /// The revision number of this update package.
    public var revisionNumber: Swift.Int32 = Swift.Int32()

    /// The last published date of the update, in (UTC) date and time.
    public var lastDeploymentChangeTime: GoogleWKT.Timestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `WindowsUpdatePackage`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WindowsUpdatePackage().with { $0.title = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let title = CodingKeys(stringValue: "title")
      static let description = CodingKeys(stringValue: "description")
      static let categories = CodingKeys(stringValue: "categories")
      static let kbArticleIds = CodingKeys(stringValue: "kbArticleIds")
      static let supportUrl = CodingKeys(stringValue: "supportUrl")
      static let moreInfoUrls = CodingKeys(stringValue: "moreInfoUrls")
      static let updateId = CodingKeys(stringValue: "updateId")
      static let revisionNumber = CodingKeys(stringValue: "revisionNumber")
      static let lastDeploymentChangeTime = CodingKeys(stringValue: "lastDeploymentChangeTime")

      static let _knownKeys: Set<Swift.String> = [
        "title",
        "description",
        "categories",
        "kbArticleIds",
        "supportUrl",
        "moreInfoUrls",
        "updateId",
        "revisionNumber",
        "lastDeploymentChangeTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .title) {
        self.title = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }
      if let value = try container.decodeIfPresent(
        [Inventory.WindowsUpdatePackage.WindowsUpdateCategory].self, forKey: .categories)
      {
        self.categories = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .kbArticleIds) {
        self.kbArticleIds = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .supportUrl) {
        self.supportUrl = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .moreInfoUrls) {
        self.moreInfoUrls = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .updateId) {
        self.updateId = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .revisionNumber) {
        self.revisionNumber = value
      }
      self.lastDeploymentChangeTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .lastDeploymentChangeTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.title, forKey: .title)
      try container.encode(self.description, forKey: .description)
      try container.encode(self.categories, forKey: .categories)
      try container.encode(self.kbArticleIds, forKey: .kbArticleIds)
      try container.encode(self.supportUrl, forKey: .supportUrl)
      try container.encode(self.moreInfoUrls, forKey: .moreInfoUrls)
      try container.encode(self.updateId, forKey: .updateId)
      try container.encode(self.revisionNumber, forKey: .revisionNumber)
      try container.encodeIfPresent(
        self.lastDeploymentChangeTime, forKey: .lastDeploymentChangeTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Categories specified by the Windows Update.
    public struct WindowsUpdateCategory: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The identifier of the windows update category.
      public var id: Swift.String = Swift.String()

      /// The name of the windows update category.
      public var name: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `WindowsUpdateCategory`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = WindowsUpdateCategory().with { $0.id = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let id = CodingKeys(stringValue: "id")
        static let name = CodingKeys(stringValue: "name")

        static let _knownKeys: Set<Swift.String> = [
          "id",
          "name",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
          self.id = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
          self.name = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.name, forKey: .name)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.osconfig.v1.Inventory.WindowsUpdatePackage.WindowsUpdateCategory"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.osconfig.v1.Inventory.WindowsUpdatePackage"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information related to a Quick Fix Engineering package.
  /// Fields are taken from Windows QuickFixEngineering Interface and match
  /// the source names:
  /// https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-quickfixengineering
  public struct WindowsQuickFixEngineeringPackage: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A short textual description of the QFE update.
    public var caption: Swift.String = Swift.String()

    /// A textual description of the QFE update.
    public var description: Swift.String = Swift.String()

    /// Unique identifier associated with a particular QFE update.
    public var hotFixId: Swift.String = Swift.String()

    /// Date that the QFE update was installed.  Mapped from installed_on field.
    public var installTime: GoogleWKT.Timestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `WindowsQuickFixEngineeringPackage`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WindowsQuickFixEngineeringPackage().with { $0.caption = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let caption = CodingKeys(stringValue: "caption")
      static let description = CodingKeys(stringValue: "description")
      static let hotFixId = CodingKeys(stringValue: "hotFixId")
      static let installTime = CodingKeys(stringValue: "installTime")

      static let _knownKeys: Set<Swift.String> = [
        "caption",
        "description",
        "hotFixId",
        "installTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .caption) {
        self.caption = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hotFixId) {
        self.hotFixId = value
      }
      self.installTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .installTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.caption, forKey: .caption)
      try container.encode(self.description, forKey: .description)
      try container.encode(self.hotFixId, forKey: .hotFixId)
      try container.encodeIfPresent(self.installTime, forKey: .installTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.osconfig.v1.Inventory.WindowsQuickFixEngineeringPackage"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Contains information about a Windows application that is retrieved from the
  /// Windows Registry. For more information about these fields, see:
  /// https://docs.microsoft.com/en-us/windows/win32/msi/uninstall-registry-key
  public struct WindowsApplication: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The name of the application or product.
    public var displayName: Swift.String = Swift.String()

    /// The version of the product or application in string format.
    public var displayVersion: Swift.String = Swift.String()

    /// The name of the manufacturer for the product or application.
    public var publisher: Swift.String = Swift.String()

    /// The last time this product received service. The value of this property
    /// is replaced each time a patch is applied or removed from the product or
    /// the command-line option is used to repair the product.
    public var installDate: GoogleType.Date? = nil

    /// The internet address for technical support.
    public var helpLink: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `WindowsApplication`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WindowsApplication().with { $0.displayName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let displayName = CodingKeys(stringValue: "displayName")
      static let displayVersion = CodingKeys(stringValue: "displayVersion")
      static let publisher = CodingKeys(stringValue: "publisher")
      static let installDate = CodingKeys(stringValue: "installDate")
      static let helpLink = CodingKeys(stringValue: "helpLink")

      static let _knownKeys: Set<Swift.String> = [
        "displayName",
        "displayVersion",
        "publisher",
        "installDate",
        "helpLink",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
        self.displayName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayVersion) {
        self.displayVersion = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .publisher) {
        self.publisher = value
      }
      self.installDate = try container.decodeIfPresent(GoogleType.Date.self, forKey: .installDate)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .helpLink) {
        self.helpLink = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.displayName, forKey: .displayName)
      try container.encode(self.displayVersion, forKey: .displayVersion)
      try container.encode(self.publisher, forKey: .publisher)
      try container.encodeIfPresent(self.installDate, forKey: .installDate)
      try container.encode(self.helpLink, forKey: .helpLink)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.osconfig.v1.Inventory.WindowsApplication"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.osconfig.v1.Inventory"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
