// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// OS Config API
///
/// The OS Config service is a server-side component that you can use to
/// manage package installations and patch jobs for virtual machine instances.
///
/// @Snippet(path: "OsConfigServiceQuickstart")
public final class OsConfigServiceClient: Clients.OsConfigServiceProtocol, Sendable {
  let inner: any Clients.OsConfigServiceStub

  /// Creates a new `OsConfigServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.OsConfigServiceStub = try Clients.OsConfigServiceTransport(options)
    inner = Clients.OsConfigServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.OsConfigServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Patch VM instances by creating and running a patch job.
  ///
  /// @Snippet(path: "OsConfigService_ExecutePatchJob")
  public func executePatchJob(
    request: ExecutePatchJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchJob {
    try await self.inner.executePatchJob(request: request, options: options)
  }

  /// Get the patch job. This can be used to track the progress of an
  /// ongoing patch job or review the details of completed jobs.
  ///
  /// @Snippet(path: "OsConfigService_GetPatchJob")
  public func getPatchJob(
    request: GetPatchJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchJob {
    try await self.inner.getPatchJob(request: request, options: options)
  }

  /// Cancel a patch job. The patch job must be active. Canceled patch jobs
  /// cannot be restarted.
  ///
  /// @Snippet(path: "OsConfigService_CancelPatchJob")
  public func cancelPatchJob(
    request: CancelPatchJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchJob {
    try await self.inner.cancelPatchJob(request: request, options: options)
  }

  /// Get a list of patch jobs.
  ///
  /// @Snippet(path: "OsConfigService_ListPatchJobs")
  public func listPatchJobs(
    request: ListPatchJobsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.ListPatchJobsResponse {
    try await self.inner.listPatchJobs(request: request, options: options)
  }

  /// Get a list of instance details for a given patch job.
  ///
  /// @Snippet(path: "OsConfigService_ListPatchJobInstanceDetails")
  public func listPatchJobInstanceDetails(
    request: ListPatchJobInstanceDetailsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.ListPatchJobInstanceDetailsResponse {
    try await self.inner.listPatchJobInstanceDetails(request: request, options: options)
  }

  /// Create an OS Config patch deployment.
  ///
  /// @Snippet(path: "OsConfigService_CreatePatchDeployment")
  public func createPatchDeployment(
    request: CreatePatchDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    try await self.inner.createPatchDeployment(request: request, options: options)
  }

  /// Get an OS Config patch deployment.
  ///
  /// @Snippet(path: "OsConfigService_GetPatchDeployment")
  public func getPatchDeployment(
    request: GetPatchDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    try await self.inner.getPatchDeployment(request: request, options: options)
  }

  /// Get a page of OS Config patch deployments.
  ///
  /// @Snippet(path: "OsConfigService_ListPatchDeployments")
  public func listPatchDeployments(
    request: ListPatchDeploymentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.ListPatchDeploymentsResponse {
    try await self.inner.listPatchDeployments(request: request, options: options)
  }

  /// Delete an OS Config patch deployment.
  ///
  /// @Snippet(path: "OsConfigService_DeletePatchDeployment")
  public func deletePatchDeployment(
    request: DeletePatchDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deletePatchDeployment(request: request, options: options)
  }

  /// Update an OS Config patch deployment.
  ///
  /// @Snippet(path: "OsConfigService_UpdatePatchDeployment")
  public func updatePatchDeployment(
    request: UpdatePatchDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    try await self.inner.updatePatchDeployment(request: request, options: options)
  }

  /// Change state of patch deployment to "PAUSED".
  /// Patch deployment in paused state doesn't generate patch jobs.
  ///
  /// @Snippet(path: "OsConfigService_PausePatchDeployment")
  public func pausePatchDeployment(
    request: PausePatchDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    try await self.inner.pausePatchDeployment(request: request, options: options)
  }

  /// Change state of patch deployment back to "ACTIVE".
  /// Patch deployment in active state continues to generate patch jobs.
  ///
  /// @Snippet(path: "OsConfigService_ResumePatchDeployment")
  public func resumePatchDeployment(
    request: ResumePatchDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    try await self.inner.resumePatchDeployment(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "OsConfigService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "OsConfigService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `OsConfigServiceClient`.
  ///
  /// To mock `OsConfigServiceClient` change your functions to receive
  /// `some OsConfigServiceProtocol` or `any OsConfigServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol OsConfigServiceProtocol: Sendable {
    /// See `OsConfigServiceClient.executePatchJob`.
    func executePatchJob(
      request: ExecutePatchJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchJob

    /// See `OsConfigServiceClient.getPatchJob`.
    func getPatchJob(
      request: GetPatchJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchJob

    /// See `OsConfigServiceClient.cancelPatchJob`.
    func cancelPatchJob(
      request: CancelPatchJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchJob

    /// See `OsConfigServiceClient.listPatchJobs`.
    func listPatchJobs(
      request: ListPatchJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListPatchJobsResponse

    /// See `OsConfigServiceClient.listPatchJobInstanceDetails`.
    func listPatchJobInstanceDetails(
      request: ListPatchJobInstanceDetailsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListPatchJobInstanceDetailsResponse

    /// See `OsConfigServiceClient.createPatchDeployment`.
    func createPatchDeployment(
      request: CreatePatchDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment

    /// See `OsConfigServiceClient.getPatchDeployment`.
    func getPatchDeployment(
      request: GetPatchDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment

    /// See `OsConfigServiceClient.listPatchDeployments`.
    func listPatchDeployments(
      request: ListPatchDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListPatchDeploymentsResponse

    /// See `OsConfigServiceClient.deletePatchDeployment`.
    func deletePatchDeployment(
      request: DeletePatchDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `OsConfigServiceClient.updatePatchDeployment`.
    func updatePatchDeployment(
      request: UpdatePatchDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment

    /// See `OsConfigServiceClient.pausePatchDeployment`.
    func pausePatchDeployment(
      request: PausePatchDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment

    /// See `OsConfigServiceClient.resumePatchDeployment`.
    func resumePatchDeployment(
      request: ResumePatchDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment

    /// See `OsConfigServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.OsConfigServiceProtocol {
  public func executePatchJob(request: ExecutePatchJobRequest) async throws
    -> GoogleCloudOSConfigV1.PatchJob
  {
    try await self.executePatchJob(request: request, options: .init())
  }

  public func executePatchJob(
    request: ExecutePatchJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchJob {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getPatchJob(request: GetPatchJobRequest) async throws
    -> GoogleCloudOSConfigV1.PatchJob
  {
    try await self.getPatchJob(request: request, options: .init())
  }

  public func getPatchJob(
    request: GetPatchJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchJob {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getPatchJob(
    name: Swift.String,
  ) async throws -> GoogleCloudOSConfigV1.PatchJob {
    let request = GetPatchJobRequest().with {
      $0.name = name
    }
    return try await self.getPatchJob(request: request)
  }

  public func cancelPatchJob(request: CancelPatchJobRequest) async throws
    -> GoogleCloudOSConfigV1.PatchJob
  {
    try await self.cancelPatchJob(request: request, options: .init())
  }

  public func cancelPatchJob(
    request: CancelPatchJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchJob {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listPatchJobs(request: ListPatchJobsRequest) async throws
    -> GoogleCloudOSConfigV1.ListPatchJobsResponse
  {
    try await self.listPatchJobs(request: request, options: .init())
  }

  public func listPatchJobs(
    request: ListPatchJobsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.ListPatchJobsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listPatchJobsByItems(
    request: ListPatchJobsRequest
  ) -> any AsyncSequence<PatchJob, Swift.Error> & Sendable {
    self.listPatchJobsByItems(request: request, options: .init())
  }

  /// Get a list of patch jobs.
  ///
  /// @Snippet(path: "OsConfigService_ListPatchJobs")
  public func listPatchJobsByItems(
    request: ListPatchJobsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<PatchJob, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudOSConfigV1.ListPatchJobsResponse in
      var request = request
      request.pageToken = token
      return try await self.listPatchJobs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listPatchJobsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<PatchJob, Swift.Error> & Sendable {
    let request = ListPatchJobsRequest().with {
      $0.parent = parent
    }
    return self.listPatchJobsByItems(request: request)
  }

  public func listPatchJobInstanceDetails(request: ListPatchJobInstanceDetailsRequest) async throws
    -> GoogleCloudOSConfigV1.ListPatchJobInstanceDetailsResponse
  {
    try await self.listPatchJobInstanceDetails(request: request, options: .init())
  }

  public func listPatchJobInstanceDetails(
    request: ListPatchJobInstanceDetailsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.ListPatchJobInstanceDetailsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listPatchJobInstanceDetailsByItems(
    request: ListPatchJobInstanceDetailsRequest
  ) -> any AsyncSequence<PatchJobInstanceDetails, Swift.Error> & Sendable {
    self.listPatchJobInstanceDetailsByItems(request: request, options: .init())
  }

  /// Get a list of instance details for a given patch job.
  ///
  /// @Snippet(path: "OsConfigService_ListPatchJobInstanceDetails")
  public func listPatchJobInstanceDetailsByItems(
    request: ListPatchJobInstanceDetailsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<PatchJobInstanceDetails, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudOSConfigV1.ListPatchJobInstanceDetailsResponse in
      var request = request
      request.pageToken = token
      return try await self.listPatchJobInstanceDetails(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listPatchJobInstanceDetailsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<PatchJobInstanceDetails, Swift.Error> & Sendable {
    let request = ListPatchJobInstanceDetailsRequest().with {
      $0.parent = parent
    }
    return self.listPatchJobInstanceDetailsByItems(request: request)
  }

  public func createPatchDeployment(request: CreatePatchDeploymentRequest) async throws
    -> GoogleCloudOSConfigV1.PatchDeployment
  {
    try await self.createPatchDeployment(request: request, options: .init())
  }

  public func createPatchDeployment(
    request: CreatePatchDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createPatchDeployment(
    parent: Swift.String,
    patchDeployment: PatchDeployment?,
    patchDeploymentId: Swift.String,
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    let request = CreatePatchDeploymentRequest().with {
      $0.parent = parent
      $0.patchDeployment = patchDeployment
      $0.patchDeploymentId = patchDeploymentId
    }
    return try await self.createPatchDeployment(request: request)
  }

  public func getPatchDeployment(request: GetPatchDeploymentRequest) async throws
    -> GoogleCloudOSConfigV1.PatchDeployment
  {
    try await self.getPatchDeployment(request: request, options: .init())
  }

  public func getPatchDeployment(
    request: GetPatchDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getPatchDeployment(
    name: Swift.String,
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    let request = GetPatchDeploymentRequest().with {
      $0.name = name
    }
    return try await self.getPatchDeployment(request: request)
  }

  public func listPatchDeployments(request: ListPatchDeploymentsRequest) async throws
    -> GoogleCloudOSConfigV1.ListPatchDeploymentsResponse
  {
    try await self.listPatchDeployments(request: request, options: .init())
  }

  public func listPatchDeployments(
    request: ListPatchDeploymentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.ListPatchDeploymentsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listPatchDeploymentsByItems(
    request: ListPatchDeploymentsRequest
  ) -> any AsyncSequence<PatchDeployment, Swift.Error> & Sendable {
    self.listPatchDeploymentsByItems(request: request, options: .init())
  }

  /// Get a page of OS Config patch deployments.
  ///
  /// @Snippet(path: "OsConfigService_ListPatchDeployments")
  public func listPatchDeploymentsByItems(
    request: ListPatchDeploymentsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<PatchDeployment, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudOSConfigV1.ListPatchDeploymentsResponse in
      var request = request
      request.pageToken = token
      return try await self.listPatchDeployments(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listPatchDeploymentsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<PatchDeployment, Swift.Error> & Sendable {
    let request = ListPatchDeploymentsRequest().with {
      $0.parent = parent
    }
    return self.listPatchDeploymentsByItems(request: request)
  }

  public func deletePatchDeployment(request: DeletePatchDeploymentRequest) async throws {
    try await self.deletePatchDeployment(request: request, options: .init())
  }

  public func deletePatchDeployment(
    request: DeletePatchDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deletePatchDeployment(
    name: Swift.String,
  ) async throws {
    let request = DeletePatchDeploymentRequest().with {
      $0.name = name
    }
    try await self.deletePatchDeployment(request: request)
  }

  public func updatePatchDeployment(request: UpdatePatchDeploymentRequest) async throws
    -> GoogleCloudOSConfigV1.PatchDeployment
  {
    try await self.updatePatchDeployment(request: request, options: .init())
  }

  public func updatePatchDeployment(
    request: UpdatePatchDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updatePatchDeployment(
    patchDeployment: PatchDeployment?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    let request = UpdatePatchDeploymentRequest().with {
      $0.patchDeployment = patchDeployment
      $0.updateMask = updateMask
    }
    return try await self.updatePatchDeployment(request: request)
  }

  public func pausePatchDeployment(request: PausePatchDeploymentRequest) async throws
    -> GoogleCloudOSConfigV1.PatchDeployment
  {
    try await self.pausePatchDeployment(request: request, options: .init())
  }

  public func pausePatchDeployment(
    request: PausePatchDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func pausePatchDeployment(
    name: Swift.String,
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    let request = PausePatchDeploymentRequest().with {
      $0.name = name
    }
    return try await self.pausePatchDeployment(request: request)
  }

  public func resumePatchDeployment(request: ResumePatchDeploymentRequest) async throws
    -> GoogleCloudOSConfigV1.PatchDeployment
  {
    try await self.resumePatchDeployment(request: request, options: .init())
  }

  public func resumePatchDeployment(
    request: ResumePatchDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func resumePatchDeployment(
    name: Swift.String,
  ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
    let request = ResumePatchDeploymentRequest().with {
      $0.name = name
    }
    return try await self.resumePatchDeployment(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
