// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class OsConfigServiceLogging: OsConfigServiceStub {
    let inner: any OsConfigServiceStub
    let logger: Logger

    public init(_ inner: any OsConfigServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-osconfig-v1"
      logger[metadataKey: "gcp.client.service"] = "osconfig"
      logger[metadataKey: "gcp.experimental.swift.client"] = "OsConfigService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func executePatchJob(
      request: ExecutePatchJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "executePatchJob",
        action: {
          (r: ExecutePatchJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.PatchJob
          in
          return try await self.inner.executePatchJob(request: r, options: o)
        })
    }

    public func getPatchJob(
      request: GetPatchJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPatchJob",
        action: {
          (r: GetPatchJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.PatchJob
          in
          return try await self.inner.getPatchJob(request: r, options: o)
        })
    }

    public func cancelPatchJob(
      request: CancelPatchJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelPatchJob",
        action: {
          (r: CancelPatchJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.PatchJob
          in
          return try await self.inner.cancelPatchJob(request: r, options: o)
        })
    }

    public func listPatchJobs(
      request: ListPatchJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListPatchJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPatchJobs",
        action: {
          (r: ListPatchJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.ListPatchJobsResponse
          in
          return try await self.inner.listPatchJobs(request: r, options: o)
        })
    }

    public func listPatchJobInstanceDetails(
      request: ListPatchJobInstanceDetailsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListPatchJobInstanceDetailsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPatchJobInstanceDetails",
        action: {
          (r: ListPatchJobInstanceDetailsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.ListPatchJobInstanceDetailsResponse
          in
          return try await self.inner.listPatchJobInstanceDetails(request: r, options: o)
        })
    }

    public func createPatchDeployment(
      request: CreatePatchDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "createPatchDeployment",
        action: {
          (r: CreatePatchDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.PatchDeployment
          in
          return try await self.inner.createPatchDeployment(request: r, options: o)
        })
    }

    public func getPatchDeployment(
      request: GetPatchDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPatchDeployment",
        action: {
          (r: GetPatchDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.PatchDeployment
          in
          return try await self.inner.getPatchDeployment(request: r, options: o)
        })
    }

    public func listPatchDeployments(
      request: ListPatchDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListPatchDeploymentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPatchDeployments",
        action: {
          (r: ListPatchDeploymentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.ListPatchDeploymentsResponse
          in
          return try await self.inner.listPatchDeployments(request: r, options: o)
        })
    }

    public func deletePatchDeployment(
      request: DeletePatchDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deletePatchDeployment",
        action: {
          (r: DeletePatchDeploymentRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deletePatchDeployment(request: r, options: o)
        })
    }

    public func updatePatchDeployment(
      request: UpdatePatchDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "updatePatchDeployment",
        action: {
          (r: UpdatePatchDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.PatchDeployment
          in
          return try await self.inner.updatePatchDeployment(request: r, options: o)
        })
    }

    public func pausePatchDeployment(
      request: PausePatchDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "pausePatchDeployment",
        action: {
          (r: PausePatchDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.PatchDeployment
          in
          return try await self.inner.pausePatchDeployment(request: r, options: o)
        })
    }

    public func resumePatchDeployment(
      request: ResumePatchDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.PatchDeployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "resumePatchDeployment",
        action: {
          (r: ResumePatchDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.PatchDeployment
          in
          return try await self.inner.resumePatchDeployment(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
