// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class OsConfigZonalServiceLogging: OsConfigZonalServiceStub {
    let inner: any OsConfigZonalServiceStub
    let logger: Logger

    public init(_ inner: any OsConfigZonalServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-osconfig-v1"
      logger[metadataKey: "gcp.client.service"] = "osconfig"
      logger[metadataKey: "gcp.experimental.swift.client"] = "OsConfigZonalService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createOspolicyAssignment(
      request: CreateOSPolicyAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createOspolicyAssignment",
        action: {
          (r: CreateOSPolicyAssignmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createOspolicyAssignment(request: r, options: o)
        })
    }

    public func updateOspolicyAssignment(
      request: UpdateOSPolicyAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateOspolicyAssignment",
        action: {
          (r: UpdateOSPolicyAssignmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateOspolicyAssignment(request: r, options: o)
        })
    }

    public func getOspolicyAssignment(
      request: GetOSPolicyAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.OSPolicyAssignment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOspolicyAssignment",
        action: {
          (r: GetOSPolicyAssignmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.OSPolicyAssignment
          in
          return try await self.inner.getOspolicyAssignment(request: r, options: o)
        })
    }

    public func listOspolicyAssignments(
      request: ListOSPolicyAssignmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListOSPolicyAssignmentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOspolicyAssignments",
        action: {
          (r: ListOSPolicyAssignmentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.ListOSPolicyAssignmentsResponse
          in
          return try await self.inner.listOspolicyAssignments(request: r, options: o)
        })
    }

    public func listOspolicyAssignmentRevisions(
      request: ListOSPolicyAssignmentRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListOSPolicyAssignmentRevisionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOspolicyAssignmentRevisions",
        action: {
          (r: ListOSPolicyAssignmentRevisionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.ListOSPolicyAssignmentRevisionsResponse
          in
          return try await self.inner.listOspolicyAssignmentRevisions(request: r, options: o)
        })
    }

    public func deleteOspolicyAssignment(
      request: DeleteOSPolicyAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOspolicyAssignment",
        action: {
          (r: DeleteOSPolicyAssignmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteOspolicyAssignment(request: r, options: o)
        })
    }

    public func getOspolicyAssignmentReport(
      request: GetOSPolicyAssignmentReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.OSPolicyAssignmentReport {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOspolicyAssignmentReport",
        action: {
          (r: GetOSPolicyAssignmentReportRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.OSPolicyAssignmentReport
          in
          return try await self.inner.getOspolicyAssignmentReport(request: r, options: o)
        })
    }

    public func listOspolicyAssignmentReports(
      request: ListOSPolicyAssignmentReportsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListOSPolicyAssignmentReportsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOspolicyAssignmentReports",
        action: {
          (r: ListOSPolicyAssignmentReportsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.ListOSPolicyAssignmentReportsResponse
          in
          return try await self.inner.listOspolicyAssignmentReports(request: r, options: o)
        })
    }

    public func getInventory(
      request: GetInventoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.Inventory {
      try await self._intercept(
        request: request,
        options: options,
        name: "getInventory",
        action: {
          (r: GetInventoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.Inventory
          in
          return try await self.inner.getInventory(request: r, options: o)
        })
    }

    public func listInventories(
      request: ListInventoriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListInventoriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listInventories",
        action: {
          (r: ListInventoriesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.ListInventoriesResponse
          in
          return try await self.inner.listInventories(request: r, options: o)
        })
    }

    public func getVulnerabilityReport(
      request: GetVulnerabilityReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.VulnerabilityReport {
      try await self._intercept(
        request: request,
        options: options,
        name: "getVulnerabilityReport",
        action: {
          (r: GetVulnerabilityReportRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.VulnerabilityReport
          in
          return try await self.inner.getVulnerabilityReport(request: r, options: o)
        })
    }

    public func listVulnerabilityReports(
      request: ListVulnerabilityReportsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOSConfigV1.ListVulnerabilityReportsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listVulnerabilityReports",
        action: {
          (r: ListVulnerabilityReportsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudOSConfigV1.ListVulnerabilityReportsResponse
          in
          return try await self.inner.listVulnerabilityReports(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
