// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A report of the OS policy assignment status for a given instance.
public struct OSPolicyAssignmentReport: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The `OSPolicyAssignmentReport` API resource name.
  ///
  /// Format:
  /// `projects/{project_number}/locations/{location}/instances/{instance_id}/osPolicyAssignments/{os_policy_assignment_id}/report`
  public var name: Swift.String = Swift.String()

  /// The Compute Engine VM instance name.
  public var instance: Swift.String = Swift.String()

  /// Reference to the `OSPolicyAssignment` API resource that the `OSPolicy`
  /// belongs to.
  ///
  /// Format:
  /// `projects/{project_number}/locations/{location}/osPolicyAssignments/{os_policy_assignment_id@revision_id}`
  public var osPolicyAssignment: Swift.String = Swift.String()

  /// Compliance data for each `OSPolicy` that is applied to the VM.
  public var osPolicyCompliances: [OSPolicyAssignmentReport.OSPolicyCompliance] = []

  /// Timestamp for when the report was last generated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Unique identifier of the last attempted run to apply the OS policies
  /// associated with this assignment on the VM.
  ///
  /// This ID is logged by the OS Config agent while applying the OS
  /// policies associated with this assignment on the VM.
  /// NOTE: If the service is unable to successfully connect to the agent for
  /// this run, then this id will not be available in the agent logs.
  public var lastRunId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OSPolicyAssignmentReport`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OSPolicyAssignmentReport().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let instance = CodingKeys(stringValue: "instance")
    static let osPolicyAssignment = CodingKeys(stringValue: "osPolicyAssignment")
    static let osPolicyCompliances = CodingKeys(stringValue: "osPolicyCompliances")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let lastRunId = CodingKeys(stringValue: "lastRunId")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "instance",
      "osPolicyAssignment",
      "osPolicyCompliances",
      "updateTime",
      "lastRunId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instance) {
      self.instance = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .osPolicyAssignment) {
      self.osPolicyAssignment = value
    }
    if let value = try container.decodeIfPresent(
      [OSPolicyAssignmentReport.OSPolicyCompliance].self, forKey: .osPolicyCompliances)
    {
      self.osPolicyCompliances = value
    }
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .lastRunId) {
      self.lastRunId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.instance, forKey: .instance)
    try container.encode(self.osPolicyAssignment, forKey: .osPolicyAssignment)
    try container.encode(self.osPolicyCompliances, forKey: .osPolicyCompliances)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.lastRunId, forKey: .lastRunId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Compliance data for an OS policy
  public struct OSPolicyCompliance: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The OS policy id
    public var osPolicyId: Swift.String = Swift.String()

    /// The compliance state of the OS policy.
    public var complianceState: OSPolicyAssignmentReport.OSPolicyCompliance.ComplianceState =
      OSPolicyAssignmentReport.OSPolicyCompliance.ComplianceState()

    /// The reason for the OS policy to be in an unknown compliance state.
    /// This field is always populated when `compliance_state` is `UNKNOWN`.
    ///
    /// If populated, the field can contain one of the following values:
    ///
    /// * `vm-not-running`: The VM was not running.
    /// * `os-policies-not-supported-by-agent`: The version of the OS Config
    /// agent running on the VM does not support running OS policies.
    /// * `no-agent-detected`: The OS Config agent is not detected for the VM.
    /// * `resource-execution-errors`: The OS Config agent encountered errors
    /// while executing one or more resources in the policy. See
    /// `os_policy_resource_compliances` for details.
    /// * `task-timeout`: The task sent to the agent to apply the policy timed
    /// out.
    /// * `unexpected-agent-state`: The OS Config agent did not report the final
    /// status of the task that attempted to apply the policy. Instead, the agent
    /// unexpectedly started working on a different task. This mostly happens
    /// when the agent or VM unexpectedly restarts while applying OS policies.
    /// * `internal-service-errors`: Internal service errors were encountered
    /// while attempting to apply the policy.
    public var complianceStateReason: Swift.String = Swift.String()

    /// Compliance data for each resource within the policy that is applied to
    /// the VM.
    public var osPolicyResourceCompliances:
      [OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `OSPolicyCompliance`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OSPolicyCompliance().with { $0.osPolicyId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let osPolicyId = CodingKeys(stringValue: "osPolicyId")
      static let complianceState = CodingKeys(stringValue: "complianceState")
      static let complianceStateReason = CodingKeys(stringValue: "complianceStateReason")
      static let osPolicyResourceCompliances = CodingKeys(
        stringValue: "osPolicyResourceCompliances")

      static let _knownKeys: Set<Swift.String> = [
        "osPolicyId",
        "complianceState",
        "complianceStateReason",
        "osPolicyResourceCompliances",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .osPolicyId) {
        self.osPolicyId = value
      }
      if let value = try container.decodeIfPresent(
        OSPolicyAssignmentReport.OSPolicyCompliance.ComplianceState.self, forKey: .complianceState)
      {
        self.complianceState = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .complianceStateReason)
      {
        self.complianceStateReason = value
      }
      if let value = try container.decodeIfPresent(
        [OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance].self,
        forKey: .osPolicyResourceCompliances)
      {
        self.osPolicyResourceCompliances = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.osPolicyId, forKey: .osPolicyId)
      try container.encode(self.complianceState, forKey: .complianceState)
      try container.encode(self.complianceStateReason, forKey: .complianceStateReason)
      try container.encode(self.osPolicyResourceCompliances, forKey: .osPolicyResourceCompliances)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Compliance data for an OS policy resource.
    public struct OSPolicyResourceCompliance: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The ID of the OS policy resource.
      public var osPolicyResourceId: Swift.String = Swift.String()

      /// Ordered list of configuration completed by the agent for the OS policy
      /// resource.
      public var configSteps:
        [OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance
          .OSPolicyResourceConfigStep] = []

      /// The compliance state of the resource.
      public var complianceState:
        OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance.ComplianceState =
          OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance.ComplianceState()

      /// A reason for the resource to be in the given compliance state.
      /// This field is always populated when `compliance_state` is `UNKNOWN`.
      ///
      /// The following values are supported when `compliance_state == UNKNOWN`
      ///
      /// * `execution-errors`: Errors were encountered by the agent while
      /// executing the resource and the compliance state couldn't be
      /// determined.
      /// * `execution-skipped-by-agent`: Resource execution was skipped by the
      /// agent because errors were encountered while executing prior resources
      /// in the OS policy.
      /// * `os-policy-execution-attempt-failed`: The execution of the OS policy
      /// containing this resource failed and the compliance state couldn't be
      /// determined.
      public var complianceStateReason: Swift.String = Swift.String()

      /// Resource specific output.
      public var output: OneOf_Output? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `OSPolicyResourceCompliance`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = OSPolicyResourceCompliance().with { $0.osPolicyResourceId = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let osPolicyResourceId = CodingKeys(stringValue: "osPolicyResourceId")
        static let configSteps = CodingKeys(stringValue: "configSteps")
        static let complianceState = CodingKeys(stringValue: "complianceState")
        static let complianceStateReason = CodingKeys(stringValue: "complianceStateReason")
        static let execResourceOutput = CodingKeys(stringValue: "execResourceOutput")

        static let _knownKeys: Set<Swift.String> = [
          "osPolicyResourceId",
          "configSteps",
          "complianceState",
          "complianceStateReason",
          "execResourceOutput",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .osPolicyResourceId)
        {
          self.osPolicyResourceId = value
        }
        if let value = try container.decodeIfPresent(
          [
            OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance
              .OSPolicyResourceConfigStep
          ].self, forKey: .configSteps)
        {
          self.configSteps = value
        }
        if let value = try container.decodeIfPresent(
          OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance.ComplianceState
            .self, forKey: .complianceState)
        {
          self.complianceState = value
        }
        if let value = try container.decodeIfPresent(
          Swift.String.self, forKey: .complianceStateReason)
        {
          self.complianceStateReason = value
        }

        var output: OneOf_Output? = nil
        let outputCheckAndSet = {
          if output != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'output'"))
          }
          output = $0
        }
        if let execResourceOutput = try container.decodeIfPresent(
          OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance.ExecResourceOutput?
            .self, forKey: .execResourceOutput)
        {
          try outputCheckAndSet(.execResourceOutput(execResourceOutput))
        }
        self.output = output
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.osPolicyResourceId, forKey: .osPolicyResourceId)
        try container.encode(self.configSteps, forKey: .configSteps)
        try container.encode(self.complianceState, forKey: .complianceState)
        try container.encode(self.complianceStateReason, forKey: .complianceStateReason)

        if let choice = self.output {
          switch choice {
          case .execResourceOutput(let value):
            try container.encode(value, forKey: .execResourceOutput)
          }
        }
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// Step performed by the OS Config agent for configuring an
      /// `OSPolicy` resource to its desired state.
      public struct OSPolicyResourceConfigStep: Codable, Equatable, GoogleWKT._AnyPackable,
        Sendable
      {
        /// Configuration step type.
        public var type:
          OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance
            .OSPolicyResourceConfigStep.Type_ = OSPolicyAssignmentReport.OSPolicyCompliance
            .OSPolicyResourceCompliance.OSPolicyResourceConfigStep.Type_()

        /// An error message recorded during the execution of this step.
        /// Only populated if errors were encountered during this step execution.
        public var errorMessage: Swift.String = Swift.String()

        @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

        /// Initialize a new instance of `OSPolicyResourceConfigStep`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = OSPolicyResourceConfigStep().with { $0.type = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private struct CodingKeys: CodingKey {
          var stringValue: Swift.String
          var intValue: Swift.Int? { nil }
          init(stringValue: Swift.String) { self.stringValue = stringValue }
          init?(intValue: Swift.Int) { nil }

          static let type = CodingKeys(stringValue: "type")
          static let errorMessage = CodingKeys(stringValue: "errorMessage")

          static let _knownKeys: Set<Swift.String> = [
            "type",
            "errorMessage",
          ]
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          if let value = try container.decodeIfPresent(
            OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance
              .OSPolicyResourceConfigStep.Type_.self, forKey: .type)
          {
            self.type = value
          }
          if let value = try container.decodeIfPresent(Swift.String.self, forKey: .errorMessage) {
            self.errorMessage = value
          }
          for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
            self._unknownFields.json[key.stringValue] = try container.decode(
              GoogleWKT.WKTValue.self, forKey: key)
          }
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.type, forKey: .type)
          try container.encode(self.errorMessage, forKey: .errorMessage)
          for (key, value) in self._unknownFields.json {
            try container.encode(value, forKey: CodingKeys(stringValue: key))
          }
        }

        /// Supported configuration step types
        ///
        /// - Note: Adding cases to this enumeration is not considered a breaking change.
        ///   Always include an `@unknown default:` case when switching over this type.
        ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
        ///   expecting specific values to remain unparsed; future releases may promote
        ///   them to named cases.
        public enum Type_: Codable, Equatable, Sendable {
          /// Default value. This value is unused.
          case unspecified
          /// Checks for resource conflicts such as schema errors.
          case validation
          /// Checks the current status of the desired state for a resource.
          case desiredStateCheck
          /// Enforces the desired state for a resource that is not in desired
          /// state.
          case desiredStateEnforcement
          /// Re-checks the status of the desired state. This check is done
          /// for a resource after the enforcement of all OS policies.
          ///
          /// This step is used to determine the final desired state status for
          /// the resource. It accounts for any resources that might have drifted
          /// from their desired state due to side effects from executing other
          /// resources.
          case desiredStateCheckPostEnforcement
          /// Encodes an unknown integer value.
          ///
          /// The most common cause for an unknown value is for the service to send
          /// a value unknown to the library. We recommend you update your library to
          /// the latest version.
          ///
          /// - Warning: Do not pattern-match specific integer values in this case;
          ///   future releases may promote them to named enum cases.
          case unknownIntValue(Int)
          /// Encodes an unknown string value.
          ///
          /// The most common cause for an unknown value is for the service to send
          /// a value unknown to the library. We recommend you update your library to
          /// the latest version.
          ///
          /// - Warning: Do not pattern-match specific string literals in this case;
          ///   future releases may promote them to named enum cases.
          case unknownStringValue(String)

          public init() {
            self = .unspecified
          }

          /// Returns the integer value associated with the enumeration.
          ///
          /// If the enumeration was initialized with an unknown string value, this returns `nil`.
          public var intValue: Int? {
            switch self {
            case .unspecified: return 0
            case .validation: return 1
            case .desiredStateCheck: return 2
            case .desiredStateEnforcement: return 3
            case .desiredStateCheckPostEnforcement: return 4
            case .unknownIntValue(let v): return v
            case .unknownStringValue: return nil
            }
          }

          /// Returns the string value (or name) associated with the enumeration.
          ///
          /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
          public var stringValue: Swift.String? {
            switch self {
            case .unspecified: return "TYPE_UNSPECIFIED"
            case .validation: return "VALIDATION"
            case .desiredStateCheck: return "DESIRED_STATE_CHECK"
            case .desiredStateEnforcement: return "DESIRED_STATE_ENFORCEMENT"
            case .desiredStateCheckPostEnforcement: return "DESIRED_STATE_CHECK_POST_ENFORCEMENT"
            case .unknownIntValue: return nil
            case .unknownStringValue(let v): return v
            }
          }

          /// Initialize from a string value.
          ///
          /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
          public init(stringValue: Swift.String) {
            switch stringValue {
            case "TYPE_UNSPECIFIED": self = .unspecified
            case "VALIDATION": self = .validation
            case "DESIRED_STATE_CHECK": self = .desiredStateCheck
            case "DESIRED_STATE_ENFORCEMENT": self = .desiredStateEnforcement
            case "DESIRED_STATE_CHECK_POST_ENFORCEMENT": self = .desiredStateCheckPostEnforcement
            default: self = .unknownStringValue(stringValue)
            }
          }

          /// Initialize from an integer value.
          ///
          /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
          public init(intValue: Int) {
            switch intValue {
            case 0: self = .unspecified
            case 1: self = .validation
            case 2: self = .desiredStateCheck
            case 3: self = .desiredStateEnforcement
            case 4: self = .desiredStateCheckPostEnforcement
            default: self = .unknownIntValue(intValue)
            }
          }

          public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            if let v = try? container.decode(Int.self) {
              self.init(intValue: v)
              return
            }
            if let s = try? container.decode(String.self) {
              if let v = Int(s) {
                self.init(intValue: v)
              } else {
                self.init(stringValue: s)
              }
              return
            }
            throw DecodingError.dataCorruptedError(
              in: container, debugDescription: "Expected enum value, must be integer or string.")
          }

          public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            switch self {
            case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
            case .validation: return try container.encode("VALIDATION")
            case .desiredStateCheck: return try container.encode("DESIRED_STATE_CHECK")
            case .desiredStateEnforcement: return try container.encode("DESIRED_STATE_ENFORCEMENT")
            case .desiredStateCheckPostEnforcement:
              return try container.encode("DESIRED_STATE_CHECK_POST_ENFORCEMENT")
            case .unknownIntValue(let v): return try container.encode(v)
            case .unknownStringValue(let v): return try container.encode(v)
            }
          }
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.osconfig.v1.OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance.OSPolicyResourceConfigStep"
        }
        public init(fromAny any: GoogleWKT.WKTAny) throws {
          self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleWKT.WKTStruct {
          return try GoogleWKT._slowAnySerialize(message: self)
        }
      }

      /// ExecResource specific output.
      public struct ExecResourceOutput: Codable, Equatable, GoogleWKT._AnyPackable,
        Sendable
      {
        /// Output from enforcement phase output file (if run).
        /// Output size is limited to 100K bytes.
        public var enforcementOutput: Foundation.Data = Foundation.Data()

        @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

        /// Initialize a new instance of `ExecResourceOutput`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = ExecResourceOutput().with { $0.enforcementOutput = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private struct CodingKeys: CodingKey {
          var stringValue: Swift.String
          var intValue: Swift.Int? { nil }
          init(stringValue: Swift.String) { self.stringValue = stringValue }
          init?(intValue: Swift.Int) { nil }

          static let enforcementOutput = CodingKeys(stringValue: "enforcementOutput")

          static let _knownKeys: Set<Swift.String> = [
            "enforcementOutput"
          ]
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          if let value = try container.decodeIfPresent(
            Foundation.Data.self, forKey: .enforcementOutput)
          {
            self.enforcementOutput = value
          }
          for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
            self._unknownFields.json[key.stringValue] = try container.decode(
              GoogleWKT.WKTValue.self, forKey: key)
          }
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.enforcementOutput, forKey: .enforcementOutput)
          for (key, value) in self._unknownFields.json {
            try container.encode(value, forKey: CodingKeys(stringValue: key))
          }
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.osconfig.v1.OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance.ExecResourceOutput"
        }
        public init(fromAny any: GoogleWKT.WKTAny) throws {
          self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleWKT.WKTStruct {
          return try GoogleWKT._slowAnySerialize(message: self)
        }
      }

      /// Possible compliance states for a resource.
      ///
      /// - Note: Adding cases to this enumeration is not considered a breaking change.
      ///   Always include an `@unknown default:` case when switching over this type.
      ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
      ///   expecting specific values to remain unparsed; future releases may promote
      ///   them to named cases.
      public enum ComplianceState: Codable, Equatable, Sendable {
        /// The resource is in an unknown compliance state.
        ///
        /// To get more details about why the policy is in this state, review
        /// the output of the `compliance_state_reason` field.
        case unknown
        /// Resource is compliant.
        case compliant
        /// Resource is non-compliant.
        case nonCompliant
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific integer values in this case;
        ///   future releases may promote them to named enum cases.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific string literals in this case;
        ///   future releases may promote them to named enum cases.
        case unknownStringValue(String)

        public init() {
          self = .unknown
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unknown: return 0
          case .compliant: return 1
          case .nonCompliant: return 2
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unknown: return "UNKNOWN"
          case .compliant: return "COMPLIANT"
          case .nonCompliant: return "NON_COMPLIANT"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ComplianceState/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "UNKNOWN": self = .unknown
          case "COMPLIANT": self = .compliant
          case "NON_COMPLIANT": self = .nonCompliant
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ComplianceState/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unknown
          case 1: self = .compliant
          case 2: self = .nonCompliant
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unknown: return try container.encode("UNKNOWN")
          case .compliant: return try container.encode("COMPLIANT")
          case .nonCompliant: return try container.encode("NON_COMPLIANT")
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      /// Resource specific output.
      public enum OneOf_Output: Codable, Equatable, Sendable {
        /// ExecResource specific output.
        indirect case execResourceOutput(
          OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance.ExecResourceOutput?
        )
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.osconfig.v1.OSPolicyAssignmentReport.OSPolicyCompliance.OSPolicyResourceCompliance"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Possible compliance states for an os policy.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum ComplianceState: Codable, Equatable, Sendable {
      /// The policy is in an unknown compliance state.
      ///
      /// Refer to the field `compliance_state_reason` to learn the exact reason
      /// for the policy to be in this compliance state.
      case unknown
      /// Policy is compliant.
      ///
      /// The policy is compliant if all the underlying resources are also
      /// compliant.
      case compliant
      /// Policy is non-compliant.
      ///
      /// The policy is non-compliant if one or more underlying resources are
      /// non-compliant.
      case nonCompliant
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unknown
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unknown: return 0
        case .compliant: return 1
        case .nonCompliant: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unknown: return "UNKNOWN"
        case .compliant: return "COMPLIANT"
        case .nonCompliant: return "NON_COMPLIANT"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ComplianceState/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "UNKNOWN": self = .unknown
        case "COMPLIANT": self = .compliant
        case "NON_COMPLIANT": self = .nonCompliant
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ComplianceState/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unknown
        case 1: self = .compliant
        case 2: self = .nonCompliant
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unknown: return try container.encode("UNKNOWN")
        case .compliant: return try container.encode("COMPLIANT")
        case .nonCompliant: return try container.encode("NON_COMPLIANT")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.osconfig.v1.OSPolicyAssignmentReport.OSPolicyCompliance"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.osconfig.v1.OSPolicyAssignmentReport"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
