// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A filter to target VM instances for patching. The targeted
/// VMs must meet all criteria specified. So if both labels and zones are
/// specified, the patch job targets only VMs with those labels and in those
/// zones.
public struct PatchInstanceFilter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Target all VM instances in the project. If true, no other criteria is
  /// permitted.
  public var all: Swift.Bool = Swift.Bool()

  /// Targets VM instances matching ANY of these GroupLabels. This allows
  /// targeting of disparate groups of VM instances.
  public var groupLabels: [PatchInstanceFilter.GroupLabel] = []

  /// Targets VM instances in ANY of these zones. Leave empty to target VM
  /// instances in any zone.
  public var zones: [Swift.String] = []

  /// Targets any of the VM instances specified. Instances are specified by their
  /// URI in the form `zones/[ZONE]/instances/[INSTANCE_NAME]`,
  /// `projects/[PROJECT_ID]/zones/[ZONE]/instances/[INSTANCE_NAME]`, or
  /// `https://www.googleapis.com/compute/v1/projects/[PROJECT_ID]/zones/[ZONE]/instances/[INSTANCE_NAME]`
  public var instances: [Swift.String] = []

  /// Targets VMs whose name starts with one of these prefixes. Similar to
  /// labels, this is another way to group VMs when targeting configs, for
  /// example prefix="prod-".
  public var instanceNamePrefixes: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PatchInstanceFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PatchInstanceFilter().with { $0.all = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let all = CodingKeys(stringValue: "all")
    static let groupLabels = CodingKeys(stringValue: "groupLabels")
    static let zones = CodingKeys(stringValue: "zones")
    static let instances = CodingKeys(stringValue: "instances")
    static let instanceNamePrefixes = CodingKeys(stringValue: "instanceNamePrefixes")

    static let _knownKeys: Set<Swift.String> = [
      "all",
      "groupLabels",
      "zones",
      "instances",
      "instanceNamePrefixes",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .all) {
      self.all = value
    }
    if let value = try container.decodeIfPresent(
      [PatchInstanceFilter.GroupLabel].self, forKey: .groupLabels)
    {
      self.groupLabels = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .zones) {
      self.zones = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .instances) {
      self.instances = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .instanceNamePrefixes)
    {
      self.instanceNamePrefixes = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.all, forKey: .all)
    try container.encode(self.groupLabels, forKey: .groupLabels)
    try container.encode(self.zones, forKey: .zones)
    try container.encode(self.instances, forKey: .instances)
    try container.encode(self.instanceNamePrefixes, forKey: .instanceNamePrefixes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Targets a group of VM instances by using their [assigned
  /// labels](https://cloud.google.com/compute/docs/labeling-resources). Labels
  /// are key-value pairs. A `GroupLabel` is a combination of labels
  /// that is used to target VMs for a patch job.
  ///
  /// For example, a patch job can target VMs that have the following
  /// `GroupLabel`: `{"env":"test", "app":"web"}`. This means that the patch job
  /// is applied to VMs that have both the labels `env=test` and `app=web`.
  public struct GroupLabel: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Compute Engine instance labels that must be present for a VM
    /// instance to be targeted by this filter.
    public var labels: [Swift.String: Swift.String] = [:]

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GroupLabel`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GroupLabel().with { $0.labels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let labels = CodingKeys(stringValue: "labels")

      static let _knownKeys: Set<Swift.String> = [
        "labels"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .labels)
      {
        self.labels = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.labels, forKey: .labels)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.osconfig.v1.PatchInstanceFilter.GroupLabel"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.osconfig.v1.PatchInstanceFilter"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
