// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Patch details for a VM instance. For more information about reviewing VM
/// instance details, see
/// [Listing all VM instance details for a specific patch
/// job](https://cloud.google.com/compute/docs/os-patch-management/manage-patch-jobs#list-instance-details).
public struct PatchJobInstanceDetails: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The instance name in the form `projects/*/zones/*/instances/*`
  public var name: Swift.String = Swift.String()

  /// The unique identifier for the instance. This identifier is
  /// defined by the server.
  public var instanceSystemId: Swift.String = Swift.String()

  /// Current state of instance patch.
  public var state: Instance.PatchState = Instance.PatchState()

  /// If the patch fails, this field provides the reason.
  public var failureReason: Swift.String = Swift.String()

  /// The number of times the agent that the agent attempts to apply the patch.
  public var attemptCount: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `PatchJobInstanceDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PatchJobInstanceDetails().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let instanceSystemId = CodingKeys(stringValue: "instanceSystemId")
    static let state = CodingKeys(stringValue: "state")
    static let failureReason = CodingKeys(stringValue: "failureReason")
    static let attemptCount = CodingKeys(stringValue: "attemptCount")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "instanceSystemId",
      "state",
      "failureReason",
      "attemptCount",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceSystemId) {
      self.instanceSystemId = value
    }
    if let value = try container.decodeIfPresent(Instance.PatchState.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .failureReason) {
      self.failureReason = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .attemptCount) {
      self.attemptCount = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.instanceSystemId, forKey: .instanceSystemId)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.failureReason, forKey: .failureReason)
    try container.encode(self.attemptCount, forKey: .attemptCount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.osconfig.v1.PatchJobInstanceDetails"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
