// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A high level representation of a patch job that is either in progress
/// or has completed.
///
/// Instance details are not included in the job. To paginate through instance
/// details, use ListPatchJobInstanceDetails.
///
/// For more information about patch jobs, see
/// [Creating patch
/// jobs](https://cloud.google.com/compute/docs/os-patch-management/create-patch-job).
public struct PatchJob: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Unique identifier for this patch job in the form
  /// `projects/*/patchJobs/*`
  public var name: Swift.String = Swift.String()

  /// Display name for this patch job. This is not a unique identifier.
  public var displayName: Swift.String = Swift.String()

  /// Description of the patch job. Length of the description is limited
  /// to 1024 characters.
  public var description: Swift.String = Swift.String()

  /// Time this patch job was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Last time this patch job was updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// The current state of the PatchJob.
  public var state: PatchJob.State = PatchJob.State()

  /// Instances to patch.
  public var instanceFilter: PatchInstanceFilter? = nil

  /// Patch configuration being applied.
  public var patchConfig: PatchConfig? = nil

  /// Duration of the patch job. After the duration ends, the
  /// patch job times out.
  public var duration: GoogleWKT.Duration? = nil

  /// Summary of instance details.
  public var instanceDetailsSummary: PatchJob.InstanceDetailsSummary? = nil

  /// If this patch job is a dry run, the agent reports that it has
  /// finished without running any updates on the VM instance.
  public var dryRun: Swift.Bool = Swift.Bool()

  /// If this patch job failed, this message provides information about the
  /// failure.
  public var errorMessage: Swift.String = Swift.String()

  /// Reflects the overall progress of the patch job in the range of
  /// 0.0 being no progress to 100.0 being complete.
  public var percentComplete: Swift.Double = Swift.Double()

  /// Output only. Name of the patch deployment that created this patch job.
  public var patchDeployment: Swift.String = Swift.String()

  /// Rollout strategy being applied.
  public var rollout: PatchRollout? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PatchJob`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PatchJob().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let state = CodingKeys(stringValue: "state")
    static let instanceFilter = CodingKeys(stringValue: "instanceFilter")
    static let patchConfig = CodingKeys(stringValue: "patchConfig")
    static let duration = CodingKeys(stringValue: "duration")
    static let instanceDetailsSummary = CodingKeys(stringValue: "instanceDetailsSummary")
    static let dryRun = CodingKeys(stringValue: "dryRun")
    static let errorMessage = CodingKeys(stringValue: "errorMessage")
    static let percentComplete = CodingKeys(stringValue: "percentComplete")
    static let patchDeployment = CodingKeys(stringValue: "patchDeployment")
    static let rollout = CodingKeys(stringValue: "rollout")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "description",
      "createTime",
      "updateTime",
      "state",
      "instanceFilter",
      "patchConfig",
      "duration",
      "instanceDetailsSummary",
      "dryRun",
      "errorMessage",
      "percentComplete",
      "patchDeployment",
      "rollout",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(PatchJob.State.self, forKey: .state) {
      self.state = value
    }
    self.instanceFilter = try container.decodeIfPresent(
      PatchInstanceFilter.self, forKey: .instanceFilter)
    self.patchConfig = try container.decodeIfPresent(PatchConfig.self, forKey: .patchConfig)
    self.duration = try container.decodeIfPresent(GoogleWKT.Duration.self, forKey: .duration)
    self.instanceDetailsSummary = try container.decodeIfPresent(
      PatchJob.InstanceDetailsSummary.self, forKey: .instanceDetailsSummary)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .dryRun) {
      self.dryRun = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .errorMessage) {
      self.errorMessage = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .percentComplete) {
      self.percentComplete = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .patchDeployment) {
      self.patchDeployment = value
    }
    self.rollout = try container.decodeIfPresent(PatchRollout.self, forKey: .rollout)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.instanceFilter, forKey: .instanceFilter)
    try container.encodeIfPresent(self.patchConfig, forKey: .patchConfig)
    try container.encodeIfPresent(self.duration, forKey: .duration)
    try container.encodeIfPresent(self.instanceDetailsSummary, forKey: .instanceDetailsSummary)
    try container.encode(self.dryRun, forKey: .dryRun)
    try container.encode(self.errorMessage, forKey: .errorMessage)
    try container.encode(self.percentComplete, forKey: .percentComplete)
    try container.encode(self.patchDeployment, forKey: .patchDeployment)
    try container.encodeIfPresent(self.rollout, forKey: .rollout)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A summary of the current patch state across all instances that this patch
  /// job affects. Contains counts of instances in different states. These states
  /// map to `InstancePatchState`. List patch job instance details to see the
  /// specific states of each instance.
  public struct InstanceDetailsSummary: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Number of instances pending patch job.
    public var pendingInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances that are inactive.
    public var inactiveInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances notified about patch job.
    public var notifiedInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances that have started.
    public var startedInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances that are downloading patches.
    public var downloadingPatchesInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances that are applying patches.
    public var applyingPatchesInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances rebooting.
    public var rebootingInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances that have completed successfully.
    public var succeededInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances that require reboot.
    public var succeededRebootRequiredInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances that failed.
    public var failedInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances that have acked and will start shortly.
    public var ackedInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances that exceeded the time out while applying the patch.
    public var timedOutInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances that are running the pre-patch step.
    public var prePatchStepInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances that are running the post-patch step.
    public var postPatchStepInstanceCount: Swift.Int64 = Swift.Int64()

    /// Number of instances that do not appear to be running the agent. Check to
    /// ensure that the agent is installed, running, and able to communicate with
    /// the service.
    public var noAgentDetectedInstanceCount: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InstanceDetailsSummary`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InstanceDetailsSummary().with { $0.pendingInstanceCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let pendingInstanceCount = CodingKeys(stringValue: "pendingInstanceCount")
      static let inactiveInstanceCount = CodingKeys(stringValue: "inactiveInstanceCount")
      static let notifiedInstanceCount = CodingKeys(stringValue: "notifiedInstanceCount")
      static let startedInstanceCount = CodingKeys(stringValue: "startedInstanceCount")
      static let downloadingPatchesInstanceCount = CodingKeys(
        stringValue: "downloadingPatchesInstanceCount")
      static let applyingPatchesInstanceCount = CodingKeys(
        stringValue: "applyingPatchesInstanceCount")
      static let rebootingInstanceCount = CodingKeys(stringValue: "rebootingInstanceCount")
      static let succeededInstanceCount = CodingKeys(stringValue: "succeededInstanceCount")
      static let succeededRebootRequiredInstanceCount = CodingKeys(
        stringValue: "succeededRebootRequiredInstanceCount")
      static let failedInstanceCount = CodingKeys(stringValue: "failedInstanceCount")
      static let ackedInstanceCount = CodingKeys(stringValue: "ackedInstanceCount")
      static let timedOutInstanceCount = CodingKeys(stringValue: "timedOutInstanceCount")
      static let prePatchStepInstanceCount = CodingKeys(stringValue: "prePatchStepInstanceCount")
      static let postPatchStepInstanceCount = CodingKeys(stringValue: "postPatchStepInstanceCount")
      static let noAgentDetectedInstanceCount = CodingKeys(
        stringValue: "noAgentDetectedInstanceCount")

      static let _knownKeys: Set<Swift.String> = [
        "pendingInstanceCount",
        "inactiveInstanceCount",
        "notifiedInstanceCount",
        "startedInstanceCount",
        "downloadingPatchesInstanceCount",
        "applyingPatchesInstanceCount",
        "rebootingInstanceCount",
        "succeededInstanceCount",
        "succeededRebootRequiredInstanceCount",
        "failedInstanceCount",
        "ackedInstanceCount",
        "timedOutInstanceCount",
        "prePatchStepInstanceCount",
        "postPatchStepInstanceCount",
        "noAgentDetectedInstanceCount",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .pendingInstanceCount)
      {
        self.pendingInstanceCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .inactiveInstanceCount)
      {
        self.inactiveInstanceCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .notifiedInstanceCount)
      {
        self.notifiedInstanceCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .startedInstanceCount)
      {
        self.startedInstanceCount = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int64.self, forKey: .downloadingPatchesInstanceCount)
      {
        self.downloadingPatchesInstanceCount = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int64.self, forKey: .applyingPatchesInstanceCount)
      {
        self.applyingPatchesInstanceCount = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int64.self, forKey: .rebootingInstanceCount)
      {
        self.rebootingInstanceCount = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int64.self, forKey: .succeededInstanceCount)
      {
        self.succeededInstanceCount = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int64.self, forKey: .succeededRebootRequiredInstanceCount)
      {
        self.succeededRebootRequiredInstanceCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .failedInstanceCount) {
        self.failedInstanceCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .ackedInstanceCount) {
        self.ackedInstanceCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .timedOutInstanceCount)
      {
        self.timedOutInstanceCount = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int64.self, forKey: .prePatchStepInstanceCount)
      {
        self.prePatchStepInstanceCount = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int64.self, forKey: .postPatchStepInstanceCount)
      {
        self.postPatchStepInstanceCount = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int64.self, forKey: .noAgentDetectedInstanceCount)
      {
        self.noAgentDetectedInstanceCount = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.pendingInstanceCount, forKey: .pendingInstanceCount)
      try container.encode(self.inactiveInstanceCount, forKey: .inactiveInstanceCount)
      try container.encode(self.notifiedInstanceCount, forKey: .notifiedInstanceCount)
      try container.encode(self.startedInstanceCount, forKey: .startedInstanceCount)
      try container.encode(
        self.downloadingPatchesInstanceCount, forKey: .downloadingPatchesInstanceCount)
      try container.encode(self.applyingPatchesInstanceCount, forKey: .applyingPatchesInstanceCount)
      try container.encode(self.rebootingInstanceCount, forKey: .rebootingInstanceCount)
      try container.encode(self.succeededInstanceCount, forKey: .succeededInstanceCount)
      try container.encode(
        self.succeededRebootRequiredInstanceCount, forKey: .succeededRebootRequiredInstanceCount)
      try container.encode(self.failedInstanceCount, forKey: .failedInstanceCount)
      try container.encode(self.ackedInstanceCount, forKey: .ackedInstanceCount)
      try container.encode(self.timedOutInstanceCount, forKey: .timedOutInstanceCount)
      try container.encode(self.prePatchStepInstanceCount, forKey: .prePatchStepInstanceCount)
      try container.encode(self.postPatchStepInstanceCount, forKey: .postPatchStepInstanceCount)
      try container.encode(self.noAgentDetectedInstanceCount, forKey: .noAgentDetectedInstanceCount)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.osconfig.v1.PatchJob.InstanceDetailsSummary"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Enumeration of the various states a patch job passes through as it
  /// executes.
  public enum State: Codable, Equatable, Sendable {
    /// State must be specified.
    case unspecified
    /// The patch job was successfully initiated.
    case started
    /// The patch job is looking up instances to run the patch on.
    case instanceLookup
    /// Instances are being patched.
    case patching
    /// Patch job completed successfully.
    case succeeded
    /// Patch job completed but there were errors.
    case completedWithErrors
    /// The patch job was canceled.
    case canceled
    /// The patch job timed out.
    case timedOut
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .started: return 1
      case .instanceLookup: return 2
      case .patching: return 3
      case .succeeded: return 4
      case .completedWithErrors: return 5
      case .canceled: return 6
      case .timedOut: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .started: return "STARTED"
      case .instanceLookup: return "INSTANCE_LOOKUP"
      case .patching: return "PATCHING"
      case .succeeded: return "SUCCEEDED"
      case .completedWithErrors: return "COMPLETED_WITH_ERRORS"
      case .canceled: return "CANCELED"
      case .timedOut: return "TIMED_OUT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "STARTED": self = .started
      case "INSTANCE_LOOKUP": self = .instanceLookup
      case "PATCHING": self = .patching
      case "SUCCEEDED": self = .succeeded
      case "COMPLETED_WITH_ERRORS": self = .completedWithErrors
      case "CANCELED": self = .canceled
      case "TIMED_OUT": self = .timedOut
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .started
      case 2: self = .instanceLookup
      case 3: self = .patching
      case 4: self = .succeeded
      case 5: self = .completedWithErrors
      case 6: self = .canceled
      case 7: self = .timedOut
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .started: return try container.encode("STARTED")
      case .instanceLookup: return try container.encode("INSTANCE_LOOKUP")
      case .patching: return try container.encode("PATCHING")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .completedWithErrors: return try container.encode("COMPLETED_WITH_ERRORS")
      case .canceled: return try container.encode("CANCELED")
      case .timedOut: return try container.encode("TIMED_OUT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.osconfig.v1.PatchJob"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
