// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents one week day in a month. An example is "the 4th Sunday".
public struct WeekDayOfMonth: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Week number in a month. 1-4 indicates the 1st to 4th week of the
  /// month. -1 indicates the last week of the month.
  public var weekOrdinal: Swift.Int32 = Swift.Int32()

  /// Required. A day of the week.
  public var dayOfWeek: GoogleType.DayOfWeek = GoogleType.DayOfWeek()

  /// Optional. Represents the number of days before or after the given week day
  /// of month that the patch deployment is scheduled for. For example if
  /// `week_ordinal` and `day_of_week` values point to the second day of the
  /// month and this `day_offset` value is set to `3`, the patch deployment takes
  /// place three days after the second Tuesday of the month. If this value is
  /// negative, for example -5, the patches are deployed five days before before
  /// the second Tuesday of the month. Allowed values are in range [-30, 30].
  public var dayOffset: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `WeekDayOfMonth`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WeekDayOfMonth().with { $0.weekOrdinal = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let weekOrdinal = CodingKeys(stringValue: "weekOrdinal")
    static let dayOfWeek = CodingKeys(stringValue: "dayOfWeek")
    static let dayOffset = CodingKeys(stringValue: "dayOffset")

    static let _knownKeys: Set<Swift.String> = [
      "weekOrdinal",
      "dayOfWeek",
      "dayOffset",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .weekOrdinal) {
      self.weekOrdinal = value
    }
    if let value = try container.decodeIfPresent(GoogleType.DayOfWeek.self, forKey: .dayOfWeek) {
      self.dayOfWeek = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .dayOffset) {
      self.dayOffset = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.weekOrdinal, forKey: .weekOrdinal)
    try container.encode(self.dayOfWeek, forKey: .dayOfWeek)
    try container.encode(self.dayOffset, forKey: .dayOffset)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.osconfig.v1.WeekDayOfMonth"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
