// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Yum patching is performed by executing `yum update`. Additional options
/// can be set to control how this is executed.
///
/// Note that not all settings are supported on all platforms.
public struct YumSettings: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Adds the `--security` flag to `yum update`. Not supported on
  /// all platforms.
  public var security: Swift.Bool = Swift.Bool()

  /// Will cause patch to run `yum update-minimal` instead.
  public var minimal: Swift.Bool = Swift.Bool()

  /// List of packages to exclude from update. These packages are excluded by
  /// using the yum `--exclude` flag.
  public var excludes: [Swift.String] = []

  /// An exclusive list of packages to be updated. These are the only packages
  /// that will be updated. If these packages are not installed, they will be
  /// ignored. This field must not be specified with any other patch
  /// configuration fields.
  public var exclusivePackages: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `YumSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = YumSettings().with { $0.security = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let security = CodingKeys(stringValue: "security")
    static let minimal = CodingKeys(stringValue: "minimal")
    static let excludes = CodingKeys(stringValue: "excludes")
    static let exclusivePackages = CodingKeys(stringValue: "exclusivePackages")

    static let _knownKeys: Set<Swift.String> = [
      "security",
      "minimal",
      "excludes",
      "exclusivePackages",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .security) {
      self.security = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .minimal) {
      self.minimal = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .excludes) {
      self.excludes = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .exclusivePackages) {
      self.exclusivePackages = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.security, forKey: .security)
    try container.encode(self.minimal, forKey: .minimal)
    try container.encode(self.excludes, forKey: .excludes)
    try container.encode(self.exclusivePackages, forKey: .exclusivePackages)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.osconfig.v1.YumSettings"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
