// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Zypper patching is performed by running `zypper patch`.
/// See also https://en.opensuse.org/SDB:Zypper_manual.
public struct ZypperSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Adds the `--with-optional` flag to `zypper patch`.
  public var withOptional: Swift.Bool = Swift.Bool()

  /// Adds the `--with-update` flag, to `zypper patch`.
  public var withUpdate: Swift.Bool = Swift.Bool()

  /// Install only patches with these categories.
  /// Common categories include security, recommended, and feature.
  public var categories: [Swift.String] = []

  /// Install only patches with these severities.
  /// Common severities include critical, important, moderate, and low.
  public var severities: [Swift.String] = []

  /// List of patches to exclude from update.
  public var excludes: [Swift.String] = []

  /// An exclusive list of patches to be updated. These are the only patches
  /// that will be installed using 'zypper patch patch:<patch_name>' command.
  /// This field must not be used with any other patch configuration fields.
  public var exclusivePatches: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ZypperSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ZypperSettings().with { $0.withOptional = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let withOptional = CodingKeys(stringValue: "withOptional")
    static let withUpdate = CodingKeys(stringValue: "withUpdate")
    static let categories = CodingKeys(stringValue: "categories")
    static let severities = CodingKeys(stringValue: "severities")
    static let excludes = CodingKeys(stringValue: "excludes")
    static let exclusivePatches = CodingKeys(stringValue: "exclusivePatches")

    static let _knownKeys: Set<Swift.String> = [
      "withOptional",
      "withUpdate",
      "categories",
      "severities",
      "excludes",
      "exclusivePatches",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .withOptional) {
      self.withOptional = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .withUpdate) {
      self.withUpdate = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .categories) {
      self.categories = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .severities) {
      self.severities = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .excludes) {
      self.excludes = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .exclusivePatches) {
      self.exclusivePatches = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.withOptional, forKey: .withOptional)
    try container.encode(self.withUpdate, forKey: .withUpdate)
    try container.encode(self.categories, forKey: .categories)
    try container.encode(self.severities, forKey: .severities)
    try container.encode(self.excludes, forKey: .excludes)
    try container.encode(self.exclusivePatches, forKey: .exclusivePatches)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.osconfig.v1.ZypperSettings"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
